### ISSUE TITLE
Fatal php 8 error

### ISSUE THREAD

**Issue by Lord64** [Sterc/seosuite#22]
**Summary**
```
Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, array given in /core/components/seosuite/model/seosuite/seosuite.class.php:779
Stack trace: #0 [internal function]: trim(Array)
#1 /core/components/seosuite/model/seosuite/seosuite.class.php(779): array_map('trim', Array)
#2 /core/components/seosuite/model/seosuite/snippets/seosuitesnippets.class.php(151): SeoSuite->renderMetaValue('[[+description]...', Array)
#3 /home/smproject/330om.smartconstractor.ru/docs/core/cache/includes/elements/modsnippet/32.include.cache.php(14): SeoSuiteSnippets->seosuiteMeta(Array)
#4 /home/smproject/330om.smartconstractor.ru/docs/core/model/modx/modscript.class.php(76): include('/home/smproject...')
#5 /home/smproject/330om.smartconstractor.ru/docs/core/model/modx/modx.class.php(1861): modScript->process(NULL)
#6 /home/smproject/330om.smartconstractor.ru/docs/core/components/seosuite/model/seosuite/plugins/seosuiteresourceplugin.class.php(238): modX->runSnippet('seosuiteMeta', Array)
#7 /home/smproject/330om.smartconstractor.ru/docs/core/components/seosuite/model/seosuite/seosuite.class.php(338): SeoSuiteResourcePlugin->onLoadWebDocument(Object(modSystemEvent), Array)
#8 /home/smproject/330om.smartconstractor.ru/docs/core/cache/includes/elements/modplugin/8.include.cache.php(11): SeoSuite->firePlugins(Object(modSystemEvent), Array)
#9 /home/smproject/330om.smartconstractor.ru/docs/core/model/modx/modscript.class.php(76): include('/home/smproject...')
#10 /home/smproject/330om.smartconstractor.ru/docs/core/model/modx/modx.class.php(1670): modScript->process(NULL)
#11 /home/smproject/330om.smartconstractor.ru/docs/core/model/modx/modrequest.class.php(133): modX->invokeEvent('OnLoadWebDocume...')
#12 /home/smproject/330om.smartconstractor.ru/docs/core/model/modx/modrequest.class.php(122): modRequest->prepareResponse()
#13 /home/smproject/330om.smartconstractor.ru/docs/core/model/modx/modx.class.php(1457): modRequest->handleRequest()
#14 /home/smproject/330om.smartconstractor.ru/docs/index.php(54): modX->handleRequest()
#15 {main} thrown in /home/smproject/330om.smartconstractor.ru/docs/core/components/seosuite/model/seosuite/seosuite.class.php on line 779
```
Environment
MODX 2.8.2-pl
SEO Suite 2.0.2-pl

**Comment by eddjimlab** [comment]
I have an error:
`[2021-05-10 16:17:00] (ERROR @ /Applications/MAMP/htdocs/geo_revo/MfDeti_core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given
[2021-05-10 16:17:00] (ERROR @ /Applications/MAMP/htdocs/geo_revo/MfDeti_core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given`
seosuite-2.0.2-pl
MODX Revolution 2.8.1-pl

**Comment by crimsonpixel** [comment]
I am also getting similar error with MODX Revoluton 2.8.2

PHP warning: trim() expects parameter 1 to be string, array given

**Comment by toro-terminator** [comment]
Same here.

**Comment by patrickatwsrn** [comment]
This error is flooding the modx error protocol:

> [2021-05-26 17:11:34] (ERROR @ /var/www/vhosts/schnelltestcenter-kaefertal.de/httpdocs/modx/core/components/seosuite/model/seosuite/seosuite.class.php : 779) PHP warning: trim() expects parameter 1 to be string, array given

Depending on the amount of people visiting your site, you can collects up to a bazillion errors in a day.

This array_map function inside renderMetaValue() seems to be the problem: 

```
    public function renderMetaValue($value, array $fields = [], $skip = null)
    {
        $processedValue     = $value;
        $unProcessedValue   = $value;

        if (!empty($value)) {
            $data = array_map('trim', $fields); // this is line 779
           ....

```

Would this work?
```
if (!empty($value)) {
   function trimMetaValue(&$value) {
      $value = trim($value); 
   }
   array_walk($data, 'trimMetaValue');
   ...
}
```

**Comment by ilyautkin** [comment]
Fixed in https://github.com/Sterc/seosuite/pull/15
