### ISSUE TITLE
Problem when switching to php version 8.0.1

### ISSUE THREAD

**Issue by Lord64** [Sterc/SEOSuite#59]
There is a problem when switching to php version 8.0.1.
```
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /home/smproject/dasha.pro/docs/core/components/seosuite/model/seosuite/snippets/seosuitesnippets.class.php:141
Stack trace:
#0 /home/smproject/dasha.pro/docs/core/components/seosuite/model/seosuite/snippets/seosuitesnippets.class.php(141): implode(Array, '\n')
#1 /home/smproject/dasha.pro/docs/core/cache/includes/elements/modsnippet/44.include.cache.php(14): SeoSuiteSnippets->seosuiteMeta(Array)
#2 /home/smproject/dasha.pro/docs/core/model/modx/modscript.class.php(76): include('/home/smproject...')
#3 /home/smproject/dasha.pro/docs/core/model/modx/modx.class.php(1865): modScript->process(NULL)
#4 /home/smproject/dasha.pro/docs/core/components/seosuite/model/seosuite/plugins/seosuiteresourceplugin.class.php(238): modX->runSnippet('seosuiteMeta', Array)
#5 /home/smproject/dasha.pro/docs/core/components/seosuite/model/seosuite/seosuite.class.php(338): SeoSuiteResourcePlugin->onLoadWebDocument(Object(modSystemEvent), Array)
#6 /home/smproject/dasha.pro/docs/core/cache/includes/elements/modplugin/21.include.cache.php(9): SeoSuite->firePlugins(Object(modSystemEvent), Array)
#7 /home/smproject/dasha.pro/docs/core/model/modx/modscript.class.php(76): include('/home/smproject...')
#8 /home/smproject/dasha.pro/docs/core/model/modx/modx.class.php(1674): modScript->process(NULL)
#9 /home/smproject/dasha.pro/docs/core/model/modx/modrequest.class.php(133): modX->invokeEvent('OnLoadWebDocume...')
#10 /home/smproject/dasha.pro/docs/core/model/modx/modrequest.class.php(122): modRequest->prepareResponse()
#11 /home/smproject/dasha.pro/docs/core/model/modx/modx.class.php(1461): modRequest->handleRequest()
#12 /home/smproject/dasha.pro/docs/index.php(54): modX->handleRequest()
#13 {main} thrown in /home/smproject/dasha.pro/docs/core/components/seosuite/model/seosuite/snippets/seosuitesnippets.class.php on line 141
```

**Comment by Bravens** [comment]
Fixed in: [b4cfd18b191c4ac609a00ef6ede77c4695932b03](https://github.com/Sterc/seosuite/commit/b4cfd18b191c4ac609a00ef6ede77c4695932b03)
