### ISSUE TITLE
SEO metas cannot save in Articles Extras

### ISSUE THREAD

**Issue by johnnydeep27** [Sterc/SEOSuite#89]
Hi, i'm encountering these errors on resources that using Articles Extras and also I cannot save the metas

`Uncaught TypeError: Cannot read properties of undefined (reading 'setValue')
    at SeoSuite.fn (resource.tab_meta.js?v=3.0.5:109:78)
    at y.Event.fire (ext-all.js:21:3547)
    at S.fireEvent (ext-all.js:21:668)
    at S.onKeyUp (ext-all.js:21:511867)
    at HTMLInputElement.A (ext-all.js:21:52931)

Uncaught TypeError: Cannot read properties of undefined (reading 'getValue')
at SeoSuite.<anonymous> (resource.tab_meta.js?v=3.0.5:430:80)`

**Comment by ilyautkin** [comment]
Related https://github.com/Sterc/seosuite/issues/55
