### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, int given

### ISSUE THREAD

**Issue by lottaar** [Sterc/SEOSuite#96]
Every now and then when using the MODX Manager the site crashes (get blank white pages) and I get the following in the server error log. It's solved by emptying the core/cache folder.

`[Sun Apr 23 13:48:58.851043 2023] [proxy_fcgi:error] [pid 1633846] [client 217.X.X.X:X] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, int given in /var/www/vhosts/mysite.com/httpdocs/core/src/Revolution/modLexicon.php:242\nStack trace:\n#0 /var/www/vhosts/mysite.com/httpdocs/core/src/Revolution/modLexicon.php(242): array_merge()\n#1 /var/www/vhosts/mysite.com/httpdocs/core/components/seosuite/src/SeoSuite.php(122): MODX\\Revolution\\modLexicon->load()\n#2 /var/www/vhosts/mysite.com/httpdocs/core/components/seosuite/bootstrap.php(13): Sterc\\SeoSuite\\SeoSuite->__construct()\n#3 /var/www/vhosts/mysite.com/httpdocs/core/vendor/pimple/pimple/src/Pimple/Container.php(122): MODX\\Revolution\\modX->{closure}()\n#4 /var/www/vhosts/mysite.com/httpdocs/core/src/Revolution/Services/Container.php(29): Pimple\\Container->offsetGet()\n#5 /var/www/vhosts/mysite.com/httpdocs/core/cache/includes/elements/modx/revolution/modplugin/25.include.cache.php(4): MODX\\Revolution\\Services\\Container->get()\n#6...', referer: https://mysite.com/manager/?a=element/chunk/update&id=50
`

MODX 3.0.4-DEV, PHP 8.2.5, SEO Suite 3.1.2

**Comment by patrickatwsrn** [comment]
This is still an issue on several instances:


`Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, int given in /var/www/vhosts/XXXX.XX/httpdocs/modx/core/src/Revolution/modLexicon.php:242 Stack trace: #0 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/src/Revolution/modLexicon.php(242): array_merge() #1 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/components/seosuite/src/SeoSuite.php(122): MODX\Revolution\modLexicon->load() #2 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/components/seosuite/bootstrap.php(13): Sterc\SeoSuite\SeoSuite->__construct() #3 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/vendor/pimple/pimple/src/Pimple/Container.php(122): MODX\Revolution\modX->{closure}() #4 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/src/Revolution/Services/Container.php(29): Pimple\Container->offsetGet() #5 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/cache/includes/elements/modx/revolution/modplugin/7.include.cache.php(4): MODX\Revolution\Services\Container->get() #6 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/src/Revolution/modScript.php(88): include('...') #7 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/src/Revolution/modX.php(1706): MODX\Revolution\modScript->process() #8 /var/www/vhosts/XXXX.XX/httpdocs/modx/core/src/Revolution/modX.php(581): MODX\Revolution\modX->invokeEvent() #9 /var/www/vhosts/XXXX.XX/httpdocs/modx/index.php(59): MODX\Revolution\modX->initialize() #10 {main} thrown in /var/www/vhosts/XXXX.XX/httpdocs/modx/core/src/Revolution/modLexicon.php on line 242
`


It's just a gut feeling, but I think this might be related to another extra running on my system.

<img width="404" alt="Image" src="https://github.com/user-attachments/assets/a6c104ba-e179-4679-ab67-6720772cb49e" />

Seo Suite 3.19, MODx 3.0.5-PL, PHP 8.2.28

**Comment by gpsietzema** [comment]
@lottaar @patrickatwsrn Is it possible one of you can temporarily disable all plugins (e.g. through setting disabled to 1 in modx_site_plugins table) and retest the same thing where it failed? If it then works, can you try and do the test again with just quickemail/mostpopular/getdata/ace/ajaxuplod disabled? Those are plugins we don't use.
